### ISSUE TITLE
how to customize the names of the inputs and outputs of a subgraph?

### ISSUE THREAD

**Issue by xueqing0622** [vivax3794/ComfyUI-Sub-Nodes#9]
how to customize the names of the inputs and outputs of a subgraph?

**Comment by MoonMoon82** [comment]
I did not find an easy and reliable way to rename the in- and output sockets.
For inputs it seems, its always depending on the name of the slot and the name of the node.

For example, I renamed cliptextencoder nodes in the node properties panel to "Pos.Prompt" and "Neg.Prompt" and text input sockets to "PosText" and "NegText":
![grafik](https://github.com/user-attachments/assets/535c00b2-1e8f-4145-9d38-b8ae92915c1d)
In the subgraph node then, it appears like this:
![grafik](https://github.com/user-attachments/assets/bedefedd-802e-4751-bc5e-365043ec06ff)
So for input sockets it is always **NameOfTheInputSocket**.**NameOfTheNode**._SomeInteger_

For output sockets I haven't figured out how to influence the name by customizing any node or socket name.
The only way I figured out is by opening the .json file and search for the socket name and change it manually.
But that way seems not to be reliable, because if you open this .json file in ComfyUI and change anything in the workflow, you need to redo all the renaming in the new .json file again.

**Comment by vivax3794** [comment]
You are correct in how the input names are determined, (idr how the output names are set at the top of my head). Supporting renaming the sockets directly is something I am gonna add when I get back home (on vacation, I released this thing at a good time xD).
Honestly idk how supporting that completely slipped my mind during the first iterations of this

**Comment by vivax3794** [comment]
You can now rename the slots on both inputs and outputs and those names will be respected when using the subgraph

**Comment by xueqing0622** [comment]
how to change name, I even change the json file, but still not work. Do you have tutor.

**Comment by xueqing0622** [comment]
ok, re name the slot input output in json file, and must rename to save another name. And it work!

**Comment by vivax3794** [comment]
You should use the builtin comfyui slot rename feature, right click on the slot (the circle) to rename stuff.

**Comment by xueqing0622** [comment]
Yes, Thx your tips! have a nice day!
